---
# Items that apply to ALL profiles:
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
#server:
 # port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.
  
---
spring:
  profiles: sentence
  application:
    name: sentence
  server:
    port: 8020
  
---
spring:
  profiles: subject
  application:
    name: subject
words: I,You,He,She,It

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
  application:
    name: noun
words: boat,book,vote,seat,backpack,partition,groundhog
